spring:
  application.name: StatefulOddsService
  main.banner-mode: "off"
  jmx.enabled: true
  jta.enabled: false

  servlet.multipart.enabled: false
  resources:
    add-mappings: false

  task:
    scheduling:
      pool.size: 1
      shutdown:
        await-termination: false
    execution:
      pool:
        core-size: 8
        max-size: 100
        keep-alive: 60s
      shutdown:
        await-termination: true
        await-termination-period: 300s

  autoconfigure.exclude:
    - org.springframework.boot.autoconfigure.validation.ValidationAutoConfiguration
    - org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
    - org.springframework.boot.autoconfigure.web.reactive.error.ErrorWebFluxAutoConfiguration

grpc:
  port: 33333
  metrics: true

server:
  port: 9000
  error:
    whitelabel.enabled: false

management:
  server:
    port: 9000
  metrics:
    web:
      server:
        request.autotime.enabled: false
    export:
      prometheus.enabled: true
    enable:
      log4j2:  false
      logback: false
      system:  false
      http.server.requests: false
  endpoint:
    health.enabled:      true
    prometheus.enabled:  true
    loggers.enabled:     true
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/"
      path-mapping:
        health: "/ping"
        prometheus: "/metrics"
        metrics: "/metric"
      exposure:
        include: "*"

  health.defaults.enabled: false
  info.defaults.enabled: false # InfoContributorAutoConfiguration

logging:
  config: classpath:logback-spring.xml
